version: '3.8'

services:
  backend:
    image: christechstarter/todo-backend:latest
    container_name: todo-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - todo-network

  frontend:
    image: christechstarter/todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - todo-network

  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - todo-network

volumes:
  postgres-data:

networks:
  todo-network:
    driver: bridge
